export const G6_GRAPH_NODE_WIDTH = 260;
export const G6_GRAPH_NODE_MIN_HEIGHT = 52;
export const G6_GRAPH_NODE_CONTENT_X = 46;
export const G6_GRAPH_NODE_CONTENT_RIGHT_PADDING = 8;
export const G6_GRAPH_NODE_TEXT_WRAP_WIDTH =
    G6_GRAPH_NODE_WIDTH - G6_GRAPH_NODE_CONTENT_X - G6_GRAPH_NODE_CONTENT_RIGHT_PADDING;
export const G6_GRAPH_NODE_METADATA_BG_WIDTH = G6_GRAPH_NODE_TEXT_WRAP_WIDTH + 4;
export const G6_GRAPH_NODE_ROW_HEIGHT = 18;
export const G6_GRAPH_NODE_H_GAP = 30;
export const G6_GRAPH_NODE_V_GAP = 10;
